// CloudBox — build-time config generator.
//
// Node is used ONLY as a build-time tool (no framework, no backend).
// Reads SUPABASE_URL + SUPABASE_ANON_KEY from real environment variables
// (Vercel Project Settings → Environment Variables during `npm run build`),
// falling back to a local `.env` file for `npm run build` on a dev machine.
// Validates them and writes the gitignored browser config `js/supabase-config.js`
// consumed via `window.CLOUDBOX_CONFIG`.
//
//   npm run build        # generate js/supabase-config.js (required before serve/deploy)
//   npx serve .          # serve the static app afterwards
//
// Security: only the client-safe anon/publishable key is ever written.
// service_role / secret keys are never read, never written, never logged.
// The real security boundary stays: Supabase Auth + PostgreSQL RLS + Storage RLS.

const fs = require("node:fs");
const path = require("node:path");

const ROOT = path.resolve(__dirname, "..");
const ENV_FILE = path.join(ROOT, ".env");
const OUT_FILE = path.join(ROOT, "js", "supabase-config.js");

// Placeholder fragments that must never reach a build (case-insensitive).
const PLACEHOLDER_PATTERNS = [
  "YOUR-PROJECT",
  "YOUR-ANON-KEY",
  "YOUR-ANON",
  "PLACEHOLDER",
  "CHANGEME",
];

function fail(msg) {
  console.error(`[cloudbox:build] ERROR: ${msg}`);
  process.exit(1);
}

// Minimal dependency-free `.env` parser: KEY=value, optional single/double
// quotes, `#` full-line comments. Only used as a local-dev fallback — real
// environment variables always win (that is how Vercel injects them).
function parseDotEnvFile(filePath) {
  const vars = {};
  let text;
  try {
    text = fs.readFileSync(filePath, "utf8");
  } catch {
    return vars;
  }
  for (const rawLine of text.split(/\r?\n/)) {
    const line = rawLine.trim();
    if (!line || line.startsWith("#")) continue;
    const m = line.match(/^([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*)$/);
    if (!m) continue;
    let val = m[2].trim();
    if (val.length >= 2 && ((val.startsWith('"') && val.endsWith('"')) || (val.startsWith("'") && val.endsWith("'")))) {
      val = val.slice(1, -1);
    } else {
      const hashIdx = val.indexOf(" #");
      if (hashIdx !== -1) val = val.slice(0, hashIdx).trim();
    }
    vars[m[1]] = val;
  }
  return vars;
}

function looksPlaceholder(value) {
  const upper = value.toUpperCase();
  return PLACEHOLDER_PATTERNS.some((p) => upper.includes(p));
}

// Best-effort guard: legacy Supabase JWT keys carry {"role": "..."} in the
// payload. Refuse anything that is not the anon key (e.g. service_role).
// New-style `sb_publishable_…` keys are opaque and skip this check.
function jwtRole(key) {
  try {
    const parts = key.split(".");
    if (parts.length !== 3) return null;
    const b64 = parts[1].replace(/-/g, "+").replace(/_/g, "/");
    const payload = JSON.parse(Buffer.from(b64, "base64").toString("utf8"));
    return typeof payload.role === "string" ? payload.role : null;
  } catch {
    return null;
  }
}

function escapeJsString(s) {
  return s
    .replace(/\\/g, "\\\\")
    .replace(/"/g, '\\"')
    .replace(/\r/g, "\\r")
    .replace(/\n/g, "\\n")
    .replace(/<\//g, "<\\/");
}

function main() {
  const fileVars = fs.existsSync(ENV_FILE) ? parseDotEnvFile(ENV_FILE) : {};

  // Real environment wins over `.env` (Vercel provides env vars to the build).
  const url = String(process.env.SUPABASE_URL ?? fileVars.SUPABASE_URL ?? "").trim();
  const key = String(process.env.SUPABASE_ANON_KEY ?? fileVars.SUPABASE_ANON_KEY ?? "").trim();

  if (!url) {
    fail(
      "SUPABASE_URL is missing. Locally: copy .env.example to .env and fill it in, then `npm run build`. " +
        "On Vercel: set SUPABASE_URL in Project Settings → Environment Variables and redeploy."
    );
  }
  if (!key) {
    fail(
      "SUPABASE_ANON_KEY is missing. Locally: copy .env.example to .env and fill it in, then `npm run build`. " +
        "On Vercel: set SUPABASE_ANON_KEY in Project Settings → Environment Variables and redeploy."
    );
  }
  if (looksPlaceholder(url)) fail("SUPABASE_URL still contains a placeholder value. Replace it with your real project URL.");
  if (looksPlaceholder(key)) fail("SUPABASE_ANON_KEY still contains a placeholder value. Replace it with your real anon/publishable key.");
  if (!url.startsWith("https://")) fail("SUPABASE_URL must start with https://.");

  const role = jwtRole(key);
  if (role && role !== "anon") {
    fail(
      `Refusing to build: the provided key has JWT role "${role}", not "anon". ` +
        "Use the Supabase anon/publishable key in the browser — never service_role or any secret key."
    );
  }

  const js =
    "// AUTO-GENERATED by `npm run build` (scripts/generate-config.js). DO NOT EDIT.\n" +
    "// Client-safe values only (anon/publishable key). Never put service_role here.\n" +
    "// Regenerate with `npm run build`. This file is gitignored.\n" +
    "window.CLOUDBOX_CONFIG = {\n" +
    `  SUPABASE_URL: "${escapeJsString(url)}",\n` +
    `  SUPABASE_ANON_KEY: "${escapeJsString(key)}"\n` +
    "};\n";

  fs.mkdirSync(path.dirname(OUT_FILE), { recursive: true });
  fs.writeFileSync(OUT_FILE, js, "utf8");

  // Never print the key. The URL is public client configuration; the key is masked.
  const maskedKey = key.length > 8 ? `${key.slice(0, 4)}…(${key.length} chars)` : `(${key.length} chars)`;
  console.log(`[cloudbox:build] OK: js/supabase-config.js generated (gitignored). SUPABASE_URL=${url} SUPABASE_ANON_KEY=${maskedKey}`);
}

main();
